### ISSUE TITLE
Add an option to not generate API Reference for submodule/subpackages

### ISSUE THREAD

**Issue by andreasfelix** [readthedocs/sphinx-autoapi#181]
I personally don't include the API reference for submodules/subpackages in my documentation, because I think of it as implementation detail. All important classes/functions are exposed at the package level.

Every time I build my documentation I get multiple warnings of the form:
```
WARNING: document isn't included in any toctree
````
Also I don't like that classes/functions which are imported at package level get documented twice.

Therefore I think it would be useful, if there would be an option to disable the API generation for sub-modules/sub-packages. Something like:
```python
autoapi_generate_api_submodules=False
autoapi_generate_api_subpackages=False
```

Another possibility would be to allow file paths in the `autoapi_dirs` option. The desired behavior could then be achieved with: 
```python
autoapi_dirs=['packagename/__init__.py']
```

**Comment by AWhetter** [comment]
Are you able to make the submodules private? By default, autoapi won't document anything private. What gets documented is "anything that is accessible through the actual package when loaded in Python.". So because the classes and functions are accessible in both the submodules and packages, it documented them in both. If you make the submodules private, then the functions and classes are only accessible in the package and so they are only documented there.

**Comment by AWhetter** [comment]
This should be possible by attaching a listener to the `autoapi-skip-member` event, and filtering the objects.

**Comment by andreasfelix** [comment]
> anything that is accessible through the actual package when loaded in Python.

Ok, I understand. So this is actually an Python issue and not specific autoapi. I was not aware that 

```python
from module import ...
```

actually binds the `module` to the package's scope and are by default accessible via `package.module`. In case anyone else is wondering this is explained [here](https://docs.python.org/3/reference/import.html#submodules).

Anyway thanks for the tip!
