### ISSUE TITLE
Python modules not found

### ISSUE THREAD

**Issue by ropeladder** [readthedocs/sphinx-autoapi#189]
I'm unable to get autoapi working in a useful way; not sure if this is a bug or just a problem with my configuration/project setup.

We have a project with modules organized like so:
```
project_root/
  - app/
    - modules/
      - my_module1.py
  - docs/
    - source/
      - conf.py
    - Makefile
```

(`app/` and `modules/` have `__init__.py` files)

Autoapi either fails to find `my_module1.py` at all (if I set `autoapi_dirs='../..'`), or (if `autoapi_dirs='../../app/modules/'`) finds it but doesn't put it in my index.html and gives all my functions a long name based on a path from somewhere above my `project_root/` dir, like `dir1.dir2.dir3.project_root.app.modules.my_module1.my_func1()`.

**Comment by AWhetter** [comment]
What behaviour are you expecting? If you're trying to document `app`, then I would specify `../../app` specifically. 
Arguably the searching shouldn't look above the directory specified in `autoapi_dirs`, but that would happen only if `dir1`, `dir2`, `dir3`, and `project_root` all contained `__init__.py` files.
Even if the searching was fixed, if you want to document only the modules in `app/modules` then you could give it `./../app/modules` specifically but it would treat all modules as submodules of a package called "modules" because it's valid to pass a package directory to `autoapi_dirs`.

I've made some clarifications in the documentation of `autoapi_dirs` to make its behaviour a bit more clear.

**Comment by AWhetter** [comment]
Without more information I there's nothing else that I can do other than the clarifications in the documentation. If you're still having problems then please let me know and we can reopen this issue.
