### ISSUE TITLE
include readme or other .md files?

### ISSUE THREAD

**Issue by dzheng256** [readthedocs/sphinx-autoapi#209]
Is there a way to include .md files in the generated python docs? I have a single large project with many distinct modules in it and am currently generating docs for all of them via a single conf.py and index.rst. However, this skips individual README.md files that are nested deeply in the project. Is it possible to include these?

**Comment by AWhetter** [comment]
I think this is enough of an unusual case that we won't add direct support for it in AutoAPI itself. However, depending on exactly what you want, I think you can achieve what you want by implementing your own `builder-inited` hook into Sphinx, getting it to copy your readme files somewhere into your Sphinx source directory. Then you can edit the templates of AutoAPI to read in those README files in some way.

I'm going to close this because it's not something we'll add support for but if there's something that we can do to make it easier then let us know!
