### ISSUE TITLE
Missing functions of package after `index`.

### ISSUE THREAD

**Issue by tannewt** [readthedocs/sphinx-autoapi#234]
Hi hi! We're using AutoAPI in CircuitPython and are hitting a weird bug where functions aren't listed in a toctree consistently. I think this has to do with the order the files are processed.

Here is a small-ish repo case. Click into the `ulab` entry and you'll see that only half of the modules have functions listed underneath even though they have functions.

![Screenshot_2020-07-27 ulab — Python documentation](https://user-images.githubusercontent.com/52649/88609228-781af500-d038-11ea-974b-95e8219ba9c8.png)

[sphinx-bug.zip](https://github.com/readthedocs/sphinx-autoapi/files/4985473/sphinx-bug.zip)

Thanks!

**Comment by AWhetter** [comment]
This issue happens because Sphinx writes out documents in alphabetical order. For example "a, index, z". z's toctree is resolved after "index" has had it's toctree both resolved and written out. Therefore any module named something that comes after "index" won't have it's toctree changes written out.
This is a problem in Sphinx so I'll submit an issue and I have a fix also.

This feature generally needs a bit of love. autodoc doesn't add to the toctree in this way and we try to mirror its behaviour as closely as possible. When using autodoc you can get toctree entries using autosummary, which we have an AutoAPI equivalent directive for, but it requires every item being documented to live in its own file that's named in a specific way. That doesn't fit with how AutoAPI works. But there's the potential for us to add toctree entries in an AutoAPI specific way and make it more flexible. Unfortunately I don't think it's technically feasible yet without https://github.com/sphinx-doc/sphinx/issues/1836

**Comment by tannewt** [comment]
Thank you!
