### ISSUE TITLE
Consider dropping support for languages other than Python

### ISSUE THREAD

**Issue by AWhetter** [readthedocs/sphinx-autoapi#248]
There doesn't seem to be much interest in being able to support the other languages. The support for other languages has been in alpha for a couple of years now but there hasn't been any progress made in terms of development on them.

Go is probably the language that gets the most use after Python, but the golangdomain extension has been abandoned for a while. It has various forks but the community hasn't settled on one. The dotnetdomain extension is in a similar situation. Javascript has built in support with Sphinx, but there hasn't been a Javascript related issue since 2017 so I'm assuming that nobody is using it.

Dropping support for the other languages would give us the flexibility to do things that make the Python experience better without having to worry about the other languages.

**Comment by jacklag** [comment]
I'm working at an integration for JavaScript based on jsdoc 3.6+ and on Typescript based on typedoc, so we can automatically generate our API docs for (Python,JavaScript, Typescript and PHP (via doxgen)).

**Comment by ashb** [comment]
Is it possible (without too much overhead) to make the langugage's pluggable? That way JS/golang can be maintained as separate modules.

@AWhetter would you also like help maintaining this module? We use it in apache/airflow and I'm willing to help you share the maintenance burden.

**Comment by AWhetter** [comment]
Making them pluggable should be easy enough from the code that we have now. It's something that I've considered. But there isn't that much code involved in the language agnostic parts of AutoAPI. There's the extension itself (https://github.com/readthedocs/sphinx-autoapi/blob/master/autoapi/extension.py) and the base object (https://github.com/readthedocs/sphinx-autoapi/blob/master/autoapi/mappers/base.py#L22). Most of the base mapper object is overridden in each language's implementation. The rest of the code is specific to one of the languages.
The main question though is, does each language benefit from there being other languages in the plugin? I think the answer is no. AutoAPI would be just as useful if it were separate plugins focused on individual languages. If we were to drop support for the other languages, people can fork AutoAPI and focus it on a single language.

**Comment by AWhetter** [comment]
> @AWhetter would you also like help maintaining this module?

Thanks for the offer. I'm always open to accepting pull requests if there's any issues that you want to tackle!

**Comment by jedbrown** [comment]
I was going to ask about the prospects of multi-language support, like documenting a C-callable library with Python bindings that can cross-reference each other. I haven't found a good answer for documenting such systems, and this seems like it could be a good basis. I have a couple projects that would be interested in using this project (and contributing C support) if there was a small multi-language example we could work from. (One of those projects uses doxygen/breathe, the other a bespoke API documentation system.)

**Comment by VincentAntoine** [comment]
Same here, would be interested to document a project with python and js.

**Comment by ain-soph** [comment]
I support to drop other languages, since I'm a pure python user using pytorch.  
Suggest the maintainer make a vote. For example, +1 emoji means support and -1 means against.  

However, I didn't see many +1 as expected though. Maybe only the ones against this change vote and leave a message, and you will get an incorrect judgment.  
It might be better to just use the analytic statistics and make the decision.

**Comment by leycec** [comment]
Ideally, AutoAPI would preserve multilingual support – because that's one of its principal draws. Since no one else does that, multilingual support is AutoAPI's definitive "killer app."

Sadly, this is all a bit of a moot point. AutoAPI isn't quite unmaintained as such, but it's not exactly actively maintained either. The initial scope was arguably *too* ambitious. I can only sob unconsolably. :sob:

**Comment by warsaw** [comment]
I sort of think that it wouldn't hurt the project too much to drop support for other than Python.  My $dayjob is where I see most non-Python being documented, and frankly Sphinx and RST aren't very popular in the non-Python world, at least IME.  We're seeing heavy adoption of Docusaurus and MD for other languages.

I still think Sphinx and RST are popular enough for Python code, but it is getting harder to justify.  MD plugins to Sphinx help.

All that said, I landed on this extension specifically because it doesn't import modules to auto generate API documentation.  That's a huge win for Python, so perhaps it's worth doubling down on that, and making the Python experience great.

**Comment by leycec** [comment]
**Shock reversal:** I now strongly support dropping everything except Python. Since this extension is on life support, focusing scarce volunteer resources on the only language most of us care about is the only sensible path forward. Let's do this!

Relatedly, have repository maintainers considered joining GitHub Sponsors? Nothing incentivizes maintenance like a viable revenue stream. :money_mouth_face:

**Comment by AWhetter** [comment]
Having thought on this some more, we will be dropping support for other languages in the next major version of AutoAPI.
Even if it were the case that this project was getting the developer time that it needs, I'm not convinced that there's enough of a benefit to supporting multiple languages in a single plugin to warrant the division in focus of developer time and constraints in design necessary to support more than one language.
Considering the reality of the current situation, I am much more motivated to make this a plugin that works really well for Python than I am to making a plugin that supports extra languages that see far less usage.
