### ISSUE TITLE
Ignore class when it was already imported in __init__.py

### ISSUE THREAD

**Issue by cdancette** [readthedocs/sphinx-autoapi#262]
Hi ! 
I have a related question to #204 , but what I would like is actually the opposite : 

I have a a/module.py with AClass, and a `a/__init__.py`. 
In the `__init__.py`, I import AClass, so that we can do do `from a import AClass` instead of `from a.module import AClass`.

I would like the autoapi to document only the `a.Aclass` and not the `a.module.AClass`, is this possible ?

Thanks !

**Comment by AWhetter** [comment]
autoapi will only document what's in `__all__` if it's defined, but that probably isn't appropriate here because I'm guessing that it makes sense for `AClass` to be in the `__all__` of `a.module`.
Your best option would be to attach an event handler to the `autoapi-skip-member` event (https://sphinx-autoapi.readthedocs.io/en/latest/reference/config.html#event-autoapi-skip-member) and get the handler to return `False` for `a.module.AClass`.

```python
def skip_member_filter(app, what, name, obj, skip, options):
    if name == "a.module.AClass":
        return False
    return None
```
