### ISSUE TITLE
Make warnings suppressable

### ISSUE THREAD

**Issue by renefritze** [readthedocs/sphinx-autoapi#275]
I've been looking into workarounds for my problems in #264. One way I came up with was to suppress all warnings from `sphinx-autoapi` for the time being. To make this possible log messages would need to be emitted with setting a `type` argument whose value can be referenced in sphinx config's `suppress_warnings` list. 
I've prototyped this here: https://github.com/readthedocs/sphinx-autoapi/compare/master...renefritze:logging_types

I'd be willing to PR this for the whole extension if that's something you'd accept. I see no downside to doing that and it would be straightforward to do with only two minor questions:
 1. There should a single source for the 'type' value. Where should that go?
 2. Should all logging functions get the `type` arg or just `warning`?

**Comment by AWhetter** [comment]
This sounds like a good idea to me.

1. I'm not fussed about there being a single source. I'm happy for us to type out the type every time. We should document it though.
2. Sphinx only uses the type and subtype on warning records so far as I can tell. So let's add them only to `warning` calls.

It would be nice to come up with appropriate subtypes as well. I'm thinking `python_import_resolution` for anything to do with resolving placeholders. `not_readable` for the warning about being unable to read a file because this is consistent with what Sphinx uses for its own subtypes. "Unknown type" should possibly be an error so leave that one out for now. "Invalid __all__ entry" could be `invalid_sources`.

**Comment by AWhetter** [comment]
Fixed via #277
