### ISSUE TITLE
Feature Request: Sphinx build should be able to generate docs from directories that contain python modules.

### ISSUE THREAD

**Issue by rgbailey** [readthedocs/sphinx-autoapi#322]
**Is your feature request related to a problem? Please describe.**
Sphinx-build fails whenever I try to generate docs from python directories i.e folders without the `__init__.py` file.

**Describe the solution you'd like**
It would be nice if the build command generates docs from directories just like it does with packages.

**Describe alternatives you've considered**
A sphinx-build option that allows it to treat directories like packages.

**Additional context**
`Extension error (autoapi.extension):
Handler <function run_autoapi at 0x7fdab9390820> for event 'builder-inited' threw an exception (exception: Relative import with too many levels (2) for module 'widgets')`

**Comment by AWhetter** [comment]
If I understand your problem correctly, the `autoapi_python_use_implicit_namespaces` option should do what you want (https://sphinx-autoapi.readthedocs.io/en/latest/reference/config.html#confval-autoapi_python_use_implicit_namespaces). If not, please can you give a more complete example of what the problem is. Including what the directory structure looks like and what autoapi settings you're using.
