### ISSUE TITLE
Does not support "#:"

### ISSUE THREAD

**Issue by mazlum** [readthedocs/sphinx-autoapi#323]
autoapi does not support "#:"

Example from Flask; in the following code not working

```python
 #: Setting this disables or force-enables the automatic options handling.
 provide_automatic_options: t.Optional[bool] = None
```

Output: 
![image](https://user-images.githubusercontent.com/5855630/152309660-f28aef88-440e-4603-a38d-d8788d9e5112.png)

**Comment by astrojuanlu** [comment]
Where is this `#:` syntax defined?

**Comment by jborean93** [comment]
It's part of Sphinx' autodoc and somewhat documented under https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html?highlight=autoattribute#directive-autoproperty.

It can be placed before, or inline after the definition for documentation as per

> For module data members and class attributes, documentation can either be put into a comment with special formatting (using a #: to start the comment instead of just #), or in a docstring after the definition. Comments need to be either on a line of their own before the definition, or immediately after the assignment on the same line. The latter form is restricted to one line only.

Defining it before allows multiple lines to be used

```python
#: Some really long winded description
#: That needs to span multiple lines
attr: int = 0

foo: str = "bar" #: Inline description that can only be 1 line
```

I've used it before for some named tuples as per https://github.com/pythongssapi/python-gssapi/blob/08fe53100e3c065b868512ba11336f3f3f128cb1/gssapi/raw/named_tuples.py#L7-L11. The generated docs from `autodoc` are https://pythongssapi.github.io/python-gssapi/stable/gssapi.raw.html?highlight=acquirecredresult#gssapi.raw.named_tuples.AcquireCredResult,

**Comment by AWhetter** [comment]
Although we usually opt for matching the behaviour of autodoc, I'm inclined not to in this case. I don't understand why Sphinx introduced an alternative syntax for documenting attributes when [PEP-257](https://www.python.org/dev/peps/pep-0257/#what-is-a-docstring) already covers how to document attributes all the way back in 2001. It seems like the syntax has existed since about Sphinx 0.6 back in 2009 (https://github.com/sphinx-doc/sphinx/commit/34a08b862e4c97c4ad530effcdf652434330490f), but unfortunately I can't find the paper trail that explains why this new syntax was added.
To support this syntax we'd need to start finding and parsing comments in source code ourselves. I'd prefer not to introduce this level of complexity for something that's specific to Sphinx autodoc, especially when there's a more conventional way of achieving the same thing.
