### ISSUE TITLE
drop setup.cfg ? 

### ISSUE THREAD

**Issue by 12rambau** [readthedocs/sphinx-autoapi#426]
I would like to refactor the configuration of the lib to move everything from setup.cfg to pyproject.toml. 

Is is a wanted feature ?

**Comment by AWhetter** [comment]
I'd like to consider moving to flit as the packaging backend. If you'd like to do that instead then I'd welcome it.
Even better if we can move the contents of the `docs` extra into the tox.ini file. We don't really need those in an extra because the dependencies are only used for development of AutoAPI.
