### ISSUE TITLE
Add option to display documentations of all overloaded function/method

### ISSUE THREAD

**Issue by Holt59** [readthedocs/sphinx-autoapi#475]
Currently, autoapi only displays the docstring of the last overload. It would be nice to have an option to display the docstring below each overload.

I know that in standard Python you should only document the implementation and not the `@overload` declaration. 

My use-case comes from documenting C bindings (from `pybind11`) using stubs where you do not have an implementation (since it is in a stub file), and where each overload can have it's own documentation and merging them is very complicated. Below is an example where it would be *very* complicated to merge the overloads:

```python
class VersionInfo:

    @overload
    def __init__(self: VersionInfo) -> None:
        """
        Construct an invalid VersionInfo.
        """
        ...
    @overload
    def __init__(
        self: VersionInfo, value: str, scheme: VersionScheme = VersionScheme.DISCOVER
    ) -> None:
        """
        Construct a VersionInfo by parsing the given string according to the given scheme.

        Args:
            value: String to parse.
            scheme: Scheme to use to parse the string.
        """
        ...
    @overload
    def __init__(
        self: VersionInfo,
        major: int,
        minor: int,
        subminor: int,
        subsubminor: int,
        release_type: ReleaseType = ReleaseType.FINAL,
    ) -> None:
        """
        Construct a VersionInfo using the given elements.

        Args:
            major: Major version.
            minor: Minor version.
            subminor: Subminor version.
            subsubminor: Subsubminor version.
            release_type: Type of release.
        """
        ...
    @overload
    def __init__(
        self: VersionInfo,
        major: int,
        minor: int,
        subminor: int,
        release_type: ReleaseType = ReleaseType.FINAL,
    ) -> None:
        """
        Construct a VersionInfo using the given elements.

        Args:
            major: Major version.
            minor: Minor version.
            subminor: Subminor version.
            release_type: Type of release.
        """
        ...
```

**Comment by AWhetter** [comment]
Not only does Python specify that you should document only the implementation, as you mention, but Sphinx itself in fact does not support this concept at all. The practical reason for this is that you couldn't have a `.. py:function` directive per overload, because they'd all have the same name and therefore you couldn't link to them uniquely.
So if AutoAPI were to support your use case, it would need to do some sort of concatenation of docstrings. Even if it did that though, you would get duplicates or conflicts in the definitions of the parameters.

pybind does some concatenation of overload docstrings itself.

```cpp
PYBIND11_MODULE(example, m) {
    m.def("add", [](int a, int b)->int { return a + b; },
      "Add two integers together.");
    m.def("add", [](float a, float b)->float { return a + b; },
      "Add two floating point numbers together.");
}
```

The above example would produce the following docstring:

```pycon
>>> help(example.add)
add(...)
 |      add(arg0: int, arg1: int) -> int
 |      add(arg0: float, arg1: float) -> float
 |      Overloaded function.
 |
 |      1. add(arg0: int, arg1: int) -> int
 |
 |      Add two integers together.
 |
 |      2. add(arg0: float, arg1: float) -> float
 |
 |      Add two floating point numbers together.
```

Given that Sphinx doesn't support this concept, that the use case goes against best practices, and the rarity of this use case, AutoAPI won't support this. If one of those things changes then we can reconsider your proposal.
I would recommend doing the pybind-like concatenation yourself, but you'll probably need to either have a single [field list](https://www.sphinx-doc.org/en/master/usage/domains/python.html#info-field-lists) of arguments (eg https://docs.python.org/3/library/stdtypes.html#range), or document them inline similar to how the Python docs do it (eg https://docs.python.org/3.10/library/subprocess.html#subprocess.Popen).
