### ISSUE TITLE
3.3.2 causing reference target not found errors for named tuples

### ISSUE THREAD

**Issue by selimt** [readthedocs/sphinx-autoapi#485]
We recently started getting CI failures and the cause was the 3.3.2 release of autoapi.

Although a class was imported and declared in the rst file, we started getting the following error:

```
sphinx.errors.SphinxWarning: /app/docstring of catalog.CatalogClient.get_taggables_unique_values:1:py:class reference target not found: catalog.schemas.UniqueValue
```

`UniqueValue` is a named tuple is declared as:

```
UniqueValue = collections.namedtuple(
    "UniqueValue", ("value", "count")
)
```

And is included in the documentation as:

```
.. autoapimodule:: catalog.schemas
    :members:  [redacted], UniqueValue
```

Going back to release 3.3.1 resolves the issue.

Thanks in advance.

**Comment by AWhetter** [comment]
Are you sure that this is caused by a change in AutoAPI? AutoAPI is documenting UniqueValue as an attribute, whereas the error message makes it look like you're trying to reference it with `:class:`. 

Either way, I'm going to get AutoAPI to report namedtuples that are created with the functional syntax as classes. Same as it would if you had created a class that inherits from namedtuple.
