### ISSUE TITLE
module is ignored when the file and the Class have the same name

### ISSUE THREAD

**Issue by 12rambau** [readthedocs/sphinx-autoapi#495]
I build an extention doumentation for Google Earth Engine and use autoapi to create the refernece pages. It makes wonders thank you very much for everything ! 

I build my documentation splitting each method in a dedicated file (`autoapi_own_page_level = "method"`) 
I recently realized a weird bug when the class and the module have the same name (in my case "Asset.py" that contains a class "Asset") then the index.rst file is not created for the module and the all module content is not documented. 

It's visible in this version of my lib: https://github.com/gee-community/geetools/tree/437dc709df197032b606ae215c2603f51bac5246
you can build it using `nox -s docs`. I have 0 clue what can lead to this problem but when I use `autoapi_keep_files = True` it's visibile that some files are missing from `docs/autoapi/geetools/Asset/` generated folder.

**Comment by AWhetter** [comment]
This is probably caused by the fact that the fully qualified name of an entity is used as a unique identifier in many places throughout the AutoAPI code. It's likely that one of either the module or class are overwriting another in a dictionary somewhere in AutoAPI and causing AutoAPI to "forget" about it.

This situation is a use case that I don't think it's worth supporting because it would require a big change to AutoAPI itself, plus such a situation causes issues in the code being documented. When a user of your library does "geetools.Asset" or "from geetools import Asset" its unclear whether the module or the class will be used.
