### ISSUE TITLE
Error, No API objects exist

### ISSUE THREAD

**Issue by ornatwork** [readthedocs/sphinx-autoapi#79]
I'm having problem getting the autoapi to work with my code.  Then I tried from the .net test directory, but i'm getting the same error there.  Any idea what I'm missing ?

> make html  
> The system cannot find the path specified.  
> sphinx-build -b html -d _build/doctrees   . _build/html  
> Running Sphinx v1.3.5  
> loading pickled environment... not yet created  
> [AutoAPI] Loading Data  
> [AutoAPI] Reading files... [100%] C:\tmp\sphinx-autoapi\tests\dotnetexample\example\Identity\src\Microsoft.AspNetCore.Identity.EntityFrameworkCore\project.json  
> [AutoAPI] Mapping Data  
> [AutoAPI] Rendering Data                                                                                                                                                                

Extension error:  
No API objects exist. Can't continue  
make: **\* [html] Error 1

**Comment by dmccaffery** [comment]
I am getting this as well and have no idea whats happening. It seems to be executing docfx, but fails after that on line: https://github.com/rtfd/sphinx-autoapi/blob/bc62802dd926c04eabf8e54adf8139753a243e52/autoapi/mappers/dotnet.py#L222

Is this project dead? I haven't seen any activity since June.

**Comment by owainc** [comment]
Happens here if I specify a filter in the docfx.json.

**Comment by agjohnson** [comment]
@dmccaffery Nope, still active, just not any time to address any support around docfx.

@ornatwork This could be an issue with either the docfx or autoapi version. I'd try install autoapi from master if you haven't already. Reinstalling docfx might help, as that project has bounced around a lot.

**Comment by dahlsailrunner** [comment]
I'm experimenting with trying to build .NET docs into an RTD sphinx project and having a rough time of it.

The documentation about how to use sphinx-autoapi are a little confusing to me and I will be happy to update them if I can get things figured out.

I have both sphinx-autoapi and docfx installed.  
I have an existing sphinx RTD project in ./docfolder.  so there are files like ./docfolder/conf.py, etc.

I then have a .net code solution in ./webapi.  The csproj is in this directory.

This is where I get confused (and I'll admit this is my first time with docfx).  I do docfx init in my code folder (./webapi) and it creates a docfx_project folder and puts a docfx.json file in there.  Since docfx_project is a subfolder of ./webapi, I add the "src": ".." to the metadata section and then if I run "docfx metadata" against my docfx.json file, I do get *.yml files in the "api" directory under docfx.

No matter what I try with the conf.py I can't seem to get anything better than "No API objects exist.  Can't continue" as described above.

Can someone clarify what my steps of the basic process *should* be and I'll give that a go?  And like I said, I would be happy to update the doc if I can get it working.

Thanks in advance (and happy to share a GitHub repo for both of these if it will help).

**Comment by huideyeren** [comment]
Hello, I have same problem.
```
~/d/d/docs ❯❯❯ make html
Running Sphinx v1.8.2
loading translations [ja]... 完了
loading intersphinx inventory from https://docs.python.org/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
/usr/local/lib/python2.7/site-packages/autoapi/extension.py:89: RemovedInSphinx20Warning: app.info() is now deprecated. Use sphinx.util.logging instead.
  app.info(bold('[AutoAPI] ') + darkgreen('Loading Data'))
[AutoAPI] Loading Data
[AutoAPI] Reading files... [100%] /Users/yusuke/dotnet-vue/dotnet_vue.Docs/docfx.json
/usr/local/lib/python2.7/site-packages/autoapi/extension.py:96: RemovedInSphinx20Warning: app.info() is now deprecated. Use sphinx.util.logging instead.
  app.info(bold('[AutoAPI] ') + darkgreen('Mapping Data'))
[AutoAPI] Mapping Data
/usr/local/lib/python2.7/site-packages/autoapi/extension.py:100: RemovedInSphinx20Warning: app.info() is now deprecated. Use sphinx.util.logging instead.
  app.info(bold('[AutoAPI] ') + darkgreen('Rendering Data'))
[AutoAPI] Rendering Data

Extension error:
No API objects exist. Can't continue
make: *** [html] Error 2
```

my repo is here.

https://github.com/huideyeren/dotnet-vue

**Comment by huideyeren** [comment]
Anyway, I tried coping the issue here and it worked.

https://github.com/dotnet/docfx/issues/3389

But, not recognized .NET domain.

Using this command. (It's workaround)

```
nuget install -OutputDirectory $TMPDIR SQLitePCLRaw.core -ExcludeVersion
for docfx in /usr/local/Cellar/docfx/*; do cp "$TMPDIR/SQLitePCLRaw.core/lib/net45/SQLitePCLRaw.core.dll" "$docfx/libexec"; done
```

**Comment by AWhetter** [comment]
Closing this now that we are dropping support for documenting languages other than Python. See #248 for more information on this decision.
